### ISSUE TITLE
Support for compiled queries

### ISSUE THREAD

**Issue by vanDonselaar** [takezoe/blocking-slick#25]
Nice project! Is there a way to support Compiled queries?

I was trying something like:
````scala
implicit class BlockingAppliedCompiledFunction[PU, R <: Rep[_], RU]
    (f: AppliedCompiledFunction[PU, R, RU]) {

  def firstOption(implicit s: JdbcBackend#Session): Option[R] = {
    val invoker = new QueryInvoker[R](f.compiledQuery)
    invoker.firstOption
  }

}
````

But the type of `R` is not what I expected. Any clue how to implement this?

**Comment by takezoe** [comment]
Oh... I've forgotten compiled query. Currently blocking-slick doesn't support it.
I will try to support it in the future version.

**Comment by vanDonselaar** [comment]
I would like to help by creating a PR, but I can't quite figure out how to implement this. I lost track with these generic `PU`, `R`, `RU`, etc. Can you offer me a hint here? Then I'll do the boring stuff. ;)

**Comment by jtjeferreira** [comment]
@vanDonselaar I did some work here https://github.com/jtjeferreira/blocking-slick/tree/compiled-query-support. I will prepare a PR during the weekend

**Comment by takezoe** [comment]
@jtjeferreira Great! I'm looking forward to your pull request 😉
