### ISSUE TITLE
Some methods are using Await.result to block

### ISSUE THREAD

**Issue by takezoe** [takezoe/blocking-slick#3]

**Comment by UnknownNPC** [comment]
What is the main problem to replace [R] with Future[R]?
```
// TODO should not be use DBIO and Future
def first(implicit session: JdbcBackend#Session): Future[R] = {
      session.database.run(a.head)
}
```

**Comment by takezoe** [comment]
@UnknownNPC To provide blocking interface.

**Comment by UnknownNPC** [comment]
@takezoe as I know we can't provide blocking interface without `Await.result` or you have some ideas?

**Comment by takezoe** [comment]
@UnknownNPC No. Simply, I would like to avoid context switching by running DBIO asynchronously. Therefore, I fixed to use the current thread for DBIO execution in 2beb8b32d9ffeccf38eb214ddc19d724b7c6ca98,
