### ISSUE TITLE
Plain sql read

### ISSUE THREAD

**Issue by nemoo** [takezoe/blocking-slick#36]
Sorry, This is more of a usage question that an issue.

I want to perform a simple read via plain sql using blocking-slick-32  0.0.8 .
This is what I currently have: 

```  
  case class Test(id: Long, name: String)

  def testSql(id: Long)(implicit session: Session): Tuple2[Long, String] = {

    implicit val getTestResult = GetResult(r => Test(r.<<, r.<<))

    sql"""select dep.id, dep.name
      from deployments dep
      where dep.id = $id""".as[(Long, String)]
  }
```
I get the error 

> type mismatch;
 found   : slick.sql.SqlStreamingAction[Vector[(Long, String)],(Long, String),slick.dbio.Effect]
 required: (Long, String)

Do you have a hint at what I might be doing wrong?

**Comment by takezoe** [comment]
Use `.first` to fetch a single result. Also you don't need to define a case class and `GetResult` if you don't need to map a result to a case class or any other forms.

```scala
def testSql(id: Long)(implicit session: Session): Tuple2[Long, String] = {
  val query = sql"""select dep.id, dep.name
    from deployments dep
    where dep.id = $id""".as[(Long, String)]

  query.first
}
```

**Comment by nemoo** [comment]
Thanks a lot! It is so simple and so obvious. Will have a look into my other codebase to see why it didn't work for me the first time.
