### ISSUE TITLE
blocking-slick-32 0.0.12 depends on Slick 3.3?

### ISSUE THREAD

**Issue by astj** [takezoe/blocking-slick#41]
Hi. We're using blocking-slick in our production.  Thank you for nice library! 

By the way, as this issue title describes, blocking-slick-32 0.0.12 depends on Slick 3.3. (Updated at #37).
I've been believing blocking-slick-**32** is for Slick 3.2 (and blocking-slick-31 is for Slick 3.1).  Am I misunderstanding naming policy?

Note: Slick 3.3 is announced not to have major API changes [in their release news](http://slick.lightbend.com/news/2019/01/30/slick-3.3.0-released.html), so practically this change does not cause problems in most cases.

**Comment by takezoe** [comment]
You're right. It should be blocking-slick-33. I released blocking-slick-32 0.0.12 built for Slick 3.3, but it was my fault. I will release blocking-slick-33 immediately to avoid confusion.

**Comment by takezoe** [comment]
Released blocking-slick-33 0.0.13. It will be available on Maven Central shortly.
https://github.com/takezoe/blocking-slick/releases/tag/SLICK-33-0.0.13

Thank you for letting me know!

**Comment by astj** [comment]
I see.  Thank you for very quick response!
