### ISSUE TITLE
blocking-slick-33 not published?

### ISSUE THREAD

**Issue by nemoo** [takezoe/blocking-slick#42]
When trying to use blocking-slick-33 with scala 2.13 (I include it like this: "com.github.takezoe" %% "blocking-slick-33" % "0.0.13",) I get these problems during the import: 
[error]   not found: https://repo1.maven.org/maven2/com/github/takezoe/blocking-slick-33_2.13/0.0.13/blocking-slick-33_2.13-0.0.13.pom
[error]   not found: https://dl.bintray.com/scalaz/releases/com/github/takezoe/blocking-slick-33_2.13/0.0.13/blocking-slick-33_2.13-0.0.13.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/github/takezoe/blocking-slick-33_2.13/0.0.13/blocking-slick-33_2.13-0.0.13.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/github/takezoe/blocking-slick-33_2.13/0.0.13/blocking-slick-33_2.13-0.0.13.pom
[error]   not found: https://jcenter.bintray.com/com/github/takezoe/blocking-slick-33_2.13/0.0.13/blocking-slick-33_2.13-0.0.13.pom

When I look at https://repo1.maven.org/maven2/com/github/takezoe/ it seems that blocking-slick-33 has never been published.

Here is a pointer to the failing branch: https://github.com/nemoo/play-slick3-example/tree/scala2.13

Would it be possible to publish it? Thanks!

**Comment by takezoe** [comment]
Sorry, I had forgotten to publish. I just published, so it will be available on the Maven central repository shortly.
